build

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -65,7 +65,7 @@ commands:
             # Logic for reverting the database state
             if (( $SUCCESS == 1 ));
             then
-              cd ~/project 3/backend
+              cd ~/project/backend
               npm install
               npm run migration:revert
             fi         
@@ -192,7 +192,6 @@ jobs:
               --parameter-overrides ID="${CIRCLE_WORKFLOW_ID:0:7}" \
               --tags project=udacity
 
-
       - run:
           name: Add back-end ip to ansible inventory
           command: |
@@ -207,7 +206,7 @@ jobs:
           paths:
             - project/.circleci/ansible/inventory.txt
 
-      # - destroy-environment 
+      - destroy-environment 
 
   configure-infrastructure:
     docker:
@@ -217,16 +216,16 @@ jobs:
       - install_awscli
       - install_ansible
       - add_ssh_keys:
-          fingerprints: ["9e:68:4e:26:c0:74:5c:9b:25:51:51:35:28:66:2a:06"]
+          fingerprints: ["15:46:82:63:84:4d:a5:34:05:b4:1a:a1:4a:4c:a1:c7"]
       - attach_workspace:
           at: ~/
       - run:
           name: Configure Server
           command: |
             cd .circleci/ansible
-            # cat inventory.txt
+            cat inventory.txt
             ansible-playbook -i inventory.txt configure-server.yml
-      # - destroy-environment
+      - destroy-environment
 
   run-migrations:
     docker:
@@ -238,15 +237,24 @@ jobs:
           name: Run migrations
           command: |
             cd backend
+            echo NODE_ENV=production  >> .env
+            echo TYPEORM_CONNECTION=postgres >> .env
+            echo TYPEORM_MIGRATIONS_DIR=./src/migrations >> .env
+            echo TYPEORM_ENTITIES=./src/modules/domain/**/*.entity.ts >> .env
+            echo TYPEORM_MIGRATIONS=./src/migrations/*.ts >> .env
+            echo TYPEORM_HOST=udapeople-db.c7eq7bxkt03m.us-east-1.rds.amazonaws.com >> .env
+            echo TYPEORM_PORT=5432 >> .env
+            echo TYPEORM_USERNAME=postgres >> .env
+            echo TYPEORM_PASSWORD=password >> .env
+            echo TYPEORM_DATABASE=glee >> .env
             npm install
             npm run migrations > migrations_dump.txt
       - run:
           name: Send migration results to kvdb.io
           command: |
-          
              if grep -q "has been executed successfully." ~/project/backend/migrations_dump.txt
              then
-                curl https://kvdb.io/WHgL4e7X6TE5H2S6QBDjpa/${KVDB_BUCKET}/migration_${CIRCLE_WORKFLOW_ID:0:7}  -d '1'
+                curl https://kvdb.io/${KVDB_BUCKET}/migration_${CIRCLE_WORKFLOW_ID:0:7}  -d '1'
                 curl --insecure https://kvdb.io/${KVDB_BUCKET}/migration_${CIRCLE_WORKFLOW_ID:0:7}
                echo " Migrations Successful "
                cat ~/project/backend/migrations_dump.txt
@@ -255,9 +263,38 @@ jobs:
                cat ~/project/backend/migrations_dump.txt
              fi 
 
-      # - destroy-environment
+      - destroy-environment
       - revert-migrations
   
+  # run-migrations:
+  #   docker:
+  #     - image: circleci/node:13.8.0
+  #   steps:
+  #     - checkout
+  #     - install_awscli
+  #     - run:
+  #         name: Run migrations
+  #         command: |
+  #           cd backend
+  #           npm install
+  #           npm run migrations > migrations_dump.txt
+  #     - run:
+  #         name: Send migration results to kvdb.io
+  #         command: |
+  #           if grep -q "has been executed successfully." ~/project/backend/migrations_dump.txt
+  #            then
+  #              curl https://kvdb.io/${KVDB_BUCKET}/migration_${CIRCLE_WORKFLOW_ID:0:7}  -d '1'
+  #              curl --insecure https://kvdb.io/${KVDB_BUCKET}/migration_${CIRCLE_WORKFLOW_ID:0:7}
+  #              echo "Migrations Successful"
+  #            else
+  #             echo "Migrations failed"
+  #             cat ~/project/backend/migrations_dump.txt
+  #            fi 
+  #     #         #  curl -k https://kvdb.io/${KVDB_BUCKET}/migration_${CIRCLE_WORKFLOW_ID:0:7}  -d '5'
+  #     #         #  curl --insecure https://kvdb.io/${KVDB_BUCKET}/migration_${CIRCLE_WORKFLOW_ID:0:7}  -d '1'
+  #     - destroy-environment
+  #     - revert-migrations
+
   deploy-frontend:
     docker:
       - image: cimg/base:stable
@@ -288,7 +325,7 @@ jobs:
             cd frontend
             npm run build
             aws s3 cp dist s3://udapeople-${CIRCLE_WORKFLOW_ID:0:7} --recursive
-      # - destroy-environment
+      - destroy-environment
       - revert-migrations
 
   deploy-backend:
@@ -300,7 +337,7 @@ jobs:
       - install_ansible
       - install_nodejs
       - add_ssh_keys:
-          fingerprints: ["15:46:82:63:84:4d:a5:34:05:b4:1a:a1:4a:4c:a1:c7"]
+          fingerprints: ["9e:68:4e:26:c0:74:5c:9b:25:51:51:35:28:66:2a:06"]
       - attach_workspace:
           at: ~/
       - restore_cache:
@@ -313,14 +350,13 @@ jobs:
       - run:
           name: Package Backend
           command: |
-           cd backend
+            cd backend
             npm run build
             tar -czf artifact.tar.gz dist/* package*
             cd ..
             pwd
             cp backend/artifact.tar.gz .circleci/ansible/roles/deploy/files
             ls .circleci/ansible/roles/deploy/files
-
       - run:
           name: Deploy backend
           command: |
@@ -330,7 +366,7 @@ jobs:
             cd .circleci/ansible
             cat inventory.txt
             ansible-playbook -i inventory.txt deploy-backend.yml
-      # - destroy-environment
+      - destroy-environment
       - revert-migrations
 
   smoke-test:
@@ -347,8 +383,8 @@ jobs:
               --filters "Name=tag:Name,Values=backend-${CIRCLE_WORKFLOW_ID:0:7}" \
               --query 'Reservations[*].Instances[*].PublicIpAddress' \
               --output text)
-            export API_URL="http://${BACKEND_PUBLIC_IP}:3030"
-            if curl "${API_URL}/api/status" | grep "ok"        
+            export API_URL=http://${BACKEND_PUBLIC_IP}:3030
+            if curl -s $API_URL/api/status | grep "ok"
             then
               exit 0
             else
@@ -357,25 +393,14 @@ jobs:
       - run:
           name: Frontend smoke test.
           command: |
-           URL="http://udapeople-${CIRCLE_WORKFLOW_ID:0:7}.s3-website-us-east-1.amazonaws.com/#/employees"            
-           echo ${URL} 
-           if curl -s ${URL} | grep "Welcome"
-           then
-                # Change this to 0 after the job fails
-              return 1
-           else
-              return 1
-           fi
-           
-           
-            # FRONTEND_WEBSITE=http://udapeople-${CIRCLE_WORKFLOW_ID:0:7}.s3-website.${AWS_DEFAULT_REGION}.amazonaws.com
-            # if curl -s $FRONTEND_WEBSITE | grep "Welcome"
-            # then
-            #   exit 0
-            # else
-            #   exit 1
-            # fi
-      # - destroy-environment
+            FRONTEND_WEBSITE=http://udapeople-${CIRCLE_WORKFLOW_ID:0:7}.s3-website.${AWS_DEFAULT_REGION}.amazonaws.com
+            if curl -s $FRONTEND_WEBSITE | grep "Welcome"
+            then
+              exit 0
+            else
+              exit 1
+            fi
+      - destroy-environment
       - revert-migrations
 
   cloudfront-update:
@@ -402,8 +427,8 @@ jobs:
               --parameter-overrides WorkflowID="${CIRCLE_WORKFLOW_ID:0:7}" \
               --tags project=udapeople
               
-  #     - destroy-environment
-  #     - revert-migrations    
+      - destroy-environment
+      - revert-migrations    
       
   cleanup:
     docker:
